# Mongo database configuration
database:
  host: localhost
  port: 27017
  user: cleve
  password: secret
  name: cleve

# If set, web access logs will be written to this file in addition to stdout.
# If not set, logs will only be written to stdout.
logfile: cleve.log

# Output watcher logs to this file in addition to stderr. If not set, logs
# will only be written to stderr.
watcher_logfile: cleve_watcher.log

# How often, in seconds, that Cleve should poll runs and analyses
# in the database for state changes. Setting this too low could
# potentially have big impact on I/O. The default is 30 seconds.
run_poll_interval: 30
analysis_poll_interval: 30

# Path to a yaml file containing the api specification
apidoc: cleve_api.yaml

# Host and port where cleve will be served
host: 127.0.0.1
port: 8080

# Base URL where webhook requests should be sent. If not defined, no
# webhook requests will be sent. The webhook API key should define
# both the header key that will be used in the request, as well as the
# API key itself, separated by `=`. If the webhook API key is not defined,
# it is assumed that no authentication is needed.
# webhook_url:
# webhook_api_key:
